@echo off
echo Starting PKT E-commerce Tutor System...

echo [1/3] Converting CSV Data to JSON...
python convert_csv_to_json.py

echo [2/3] Checking and Ingesting PDFs (RAG)...
python ingest_pdfs.py

echo [3/3] Launching Web Server...
python main.py
pause
